development:
  adapter: mysql2
  database: blogs_development
  pool: 5
  timeout: 5000
  username: root
  password: password
  socket: /tmp/mysql.sock

#development:
#  adapter: sqlite3
#  database: db/develop.db
#  pool: 5
#  timeout: 5000

